turbot/steampipe-mod-gcp-compliance

- README.md
- mod.sp
> update image link in README and description in mod.sp closes #3

- cis_v120/docs/cis_v120_1.md
- cis_v120/docs/cis_v120_1_1.md
- cis_v120/docs/cis_v120_1_10.md
- cis_v120/docs/cis_v120_1_11.md
- cis_v120/docs/cis_v120_1_12.md
- cis_v120/docs/cis_v120_1_13.md
- cis_v120/docs/cis_v120_1_14.md
- cis_v120/docs/cis_v120_1_15.md
- cis_v120/docs/cis_v120_1_2.md
- cis_v120/docs/cis_v120_1_3.md
- cis_v120/docs/cis_v120_1_4.md
- cis_v120/docs/cis_v120_1_5.md
- cis_v120/docs/cis_v120_1_6.md
- cis_v120/docs/cis_v120_1_7.md
- cis_v120/docs/cis_v120_1_8.md
- cis_v120/docs/cis_v120_1_9.md
- cis_v120/section1.sp
> Add CIS v1.3.0 section 1 docs. Closes #2

- cis_v120/docs/cis_v120_2.md
- cis_v120/docs/cis_v120_2_1.md
- cis_v120/docs/cis_v120_2_10.md
- cis_v120/docs/cis_v120_2_11.md
- cis_v120/docs/cis_v120_2_12.md
- cis_v120/docs/cis_v120_2_2.md
- cis_v120/docs/cis_v120_2_3.md
- cis_v120/docs/cis_v120_2_4.md
- cis_v120/docs/cis_v120_2_5.md
- cis_v120/docs/cis_v120_2_6.md
- cis_v120/docs/cis_v120_2_7.md
- cis_v120/docs/cis_v120_2_8.md
- cis_v120/docs/cis_v120_2_9.md
- cis_v120/section2.sp
> Add CIS v1.2.0 section 2 docs . Closes #7

- cis_v120/docs/cis_v120_3.md
- cis_v120/docs/cis_v120_3_1.md
- cis_v120/docs/cis_v120_3_10.md
- cis_v120/docs/cis_v120_3_2.md
- cis_v120/docs/cis_v120_3_3.md
- cis_v120/docs/cis_v120_3_4.md
- cis_v120/docs/cis_v120_3_5.md
- cis_v120/docs/cis_v120_3_6.md
- cis_v120/docs/cis_v120_3_7.md
- cis_v120/docs/cis_v120_3_8.md
- cis_v120/docs/cis_v120_3_9.md
- cis_v120/section3.sp
> Add CIS v1.2.0 section 3 docs. Closes #6

- cis_v120/docs/cis_v120_5.md
- cis_v120/docs/cis_v120_5_1.md
- cis_v120/docs/cis_v120_5_2.md
- cis_v120/section5.sp
> Add CIS v1.2.0 section 5 docs . Closes #12

- cis_v120/docs/cis_v120_6.md
- cis_v120/docs/cis_v120_6_1.md
- cis_v120/docs/cis_v120_6_1_1.md
- cis_v120/docs/cis_v120_6_1_2.md
- cis_v120/docs/cis_v120_6_1_3.md
- cis_v120/section6.sp
> Add CIS v1.2.0 section 6.1.1 docs . Closes #1

- cis_v120/docs/cis_v120_4.md
- cis_v120/docs/cis_v120_4_1.md
- cis_v120/docs/cis_v120_4_10.md
- cis_v120/docs/cis_v120_4_11.md
- cis_v120/docs/cis_v120_4_2.md
- cis_v120/docs/cis_v120_4_3.md
- cis_v120/docs/cis_v120_4_4.md
- cis_v120/docs/cis_v120_4_5.md
- cis_v120/docs/cis_v120_4_6.md
- cis_v120/docs/cis_v120_4_7.md
- cis_v120/docs/cis_v120_4_8.md
- cis_v120/docs/cis_v120_4_9.md
- cis_v120/section4.sp
> Add CIS v1.2.0 section 4 docs. Closes #11

- cis_v120/cis_v120_7.md
- cis_v120/cis_v120_7_1.md
- cis_v120/cis_v120_7_2.md
- cis_v120/cis_v120_7_3.md
- cis_v120/section7.sp
> Add CIS v1.2.0 section 7 docs. Closes #25

- cis_v120/docs/cis_v120_6_3.md
- cis_v120/docs/cis_v120_6_3_1.md
- cis_v120/docs/cis_v120_6_3_2.md
- cis_v120/docs/cis_v120_6_3_3.md
- cis_v120/docs/cis_v120_6_3_4.md
- cis_v120/docs/cis_v120_6_3_5.md
- cis_v120/docs/cis_v120_6_3_6.md
- cis_v120/docs/cis_v120_6_3_7.md
- cis_v120/docs/cis_v120_6_4.md
- cis_v120/docs/cis_v120_6_5.md
- cis_v120/docs/cis_v120_6_6.md
- cis_v120/docs/cis_v120_6_7.md
- cis_v120/section6.sp
> Add CIS v1.2.0 section 6.3 - 6.7 docs. Closes #21

- cis_v120/docs/cis_v120_6_2.md
- cis_v120/docs/cis_v120_6_2_1.md
- cis_v120/docs/cis_v120_6_2_10.md
- cis_v120/docs/cis_v120_6_2_11.md
- cis_v120/docs/cis_v120_6_2_12.md
- cis_v120/docs/cis_v120_6_2_13.md
- cis_v120/docs/cis_v120_6_2_14.md
- cis_v120/docs/cis_v120_6_2_15.md
- cis_v120/docs/cis_v120_6_2_16.md
- cis_v120/docs/cis_v120_6_2_2.md
- cis_v120/docs/cis_v120_6_2_3.md
- cis_v120/docs/cis_v120_6_2_4.md
- cis_v120/docs/cis_v120_6_2_5.md
- cis_v120/docs/cis_v120_6_2_6.md
- cis_v120/docs/cis_v120_6_2_7.md
- cis_v120/docs/cis_v120_6_2_8.md
- cis_v120/docs/cis_v120_6_2_9.md
- cis_v120/section6.sp
> Add CIS v1.2.0 section 6.2.1 - 6.2.16 docs . Closes #13

- cis_v120/section_1.sp
- query/iam/iam_user_uses_corporate_login_credentials.sql
- query/iam/iam_user_with_corporate_login_credentials.sql
**_Added_**
- Check for `1.1 Ensure that corporate login credentials are used`
> Add check for CIS v1.2.0 Section 1.1. Closes #37

- query/iam/iam_user_separation_of_duty_enforced.sql
> Fix queries with unnecessary quotes (""). Fixes #41

- README.md
- docs/index.md
> Update GitHub link in the README file

- CHANGELOG.md
> Update CHANGELOG with the query cleanup release note

- query/kubernetes/kubernetes_cluster_private_cluster_config_enabled.sql
> Fix the kubernetes_cluster_private_cluster_config_enabled query to correctly reflect the status closes #58

- cft_scorecard_v1/cft_scorecard.sp
- cis_v120/cis.sp
- cis_v120/section_1.sp
- cis_v120/section_2.sp
- cis_v120/section_3.sp
- cis_v120/section_4.sp
- cis_v120/section_5.sp
- cis_v120/section_6.sp
- cis_v120/section_7.sp
- forseti_security_v226/forseti_security.sp
- mod.sp
- policy_bundle/appengine.sp
- policy_bundle/bigquery.sp
- policy_bundle/compute.sp
- policy_bundle/dns.sp
- policy_bundle/iam.sp
- policy_bundle/kms.sp
- policy_bundle/kubernetes.sp
- policy_bundle/sql.sp
- policy_bundle/storage.sp
> Update benchmark and control tags for compatibility with dashboard page

- query/kms/kms_key_separation_of_duties_enforced.sql
> Incorrect logic in CIS 1.09 Closes #79

- cis_v130/section_3.sp
- cis_v200/section_3.sp
- policy_bundle/compute.sp
> Fix CIS v1.3.0 and v2.0.0 3.10 control to include 35.235.240.0/20 and port 443 closes #100

- policy_bundle/iam.sp
> Fix CIS Control cis_v120_1_1 producing incorrect results for corporate login credentials Fixes #84

- cis_v120/section_1.sp
- cis_v130/section_1.sp
- cis_v200/section_1.sp
- policy_bundle/iam.sp
- adding query for cis v200_1_15
> Query for cis v200_1_15

- policy_bundle/logging.sp
This commit fixes a bug which occurs when the dashboard is ran against multiple GCP projects (for instance, when using an aggregator in the search-path).
Only the last of the N project would be reported as having correctly configured log sinks although every other project is also having log sinks.
> Fixed a bug where only the last project of N projects would return correctly configured log sinks

- cis_v120/section_1.sp
- cis_v130/section_1.sp
- cis_v200/section_1.sp
- policy_bundle/iam.sp
this is a generic query to check if no restrictions are applied to API keys and needs to be fine tuned for cis_v200_1_13 and cis_v200_1_14
https://github.com/turbot/steampipe-mod-gcp-compliance/issues/114
> Add iam_api_key_restricts_apis and iam_api_key_restricts_websites_hosts_apps queries

- mod.sp
- policy_bundle/kms.sp
> Query kms_key_rotated_within_90_day modification to verify key status closes #118

- mod.sp
> Update mod.sp to address deprecation warning closes #129

- policy_bundle/kms.sp
> CIS 2.0.0 Control 1.11 Query is wrong closes #131

- policy_bundle/compute.sp
Results 
```
+ 3.10 Use Identity Aware Proxy (IAP) to Ensure Only Traffic From Google IP Addresses are 'Allowed' ................................................................................. 3 / 4 [==========]
| 
ALARM: default-allow-https IAP not configured to allow traffic from Google IP addresses. ........................................................................................... global demo-aaa
ALARM: default-allow-http IAP not configured to allow traffic from Google IP addresses. ............................................................................................ global demo-aaa
ALARM: tets56 IAP not configured to allow traffic from Google IP addresses. ........................................................................................................ global …
```
> Fixed compute_firewall_allow_tcp_connections_proxied_by_iap query of cis_v200_3_10

- CHANGELOG.md
> Add CHANGELOG for v0.25

- all_controls/all_controls.sp
> Fixed the hierarchy in the benchmark list by properly integrating 'Cloud Functions' into its relevant benchmark

- policy_bundle/logging.sp
> Queries between Control 2.4 and 2.11 of CIS v2.0.0 don't support multiple GCP projects? closes #149

- policy_bundle/logging.sp
- policy_bundle/project.sp
- policy_bundle/storage.sp
> Query optimization

- policy_bundle/cloudfunction.sp
> Fix query cloudfunction_function_no_deployments_manager_permission

- README.md
- docs/index.md
- hipaa/164_308/164_308.sp
- hipaa/164_308/164_308_a_1_ii.sp
- hipaa/164_308/164_308_a_3_i.sp
- hipaa/164_308/164_308_a_3_ii.sp
- hipaa/164_308/164_308_a_7_ii.sp
- hipaa/164_310/164_310.sp
- hipaa/164_310/164_310_d_2_iii.sp
- hipaa/164_312/164_312.sp
- hipaa/164_312/164_312_a_1.sp
- hipaa/164_312/164_312_a_2_iv.sp
- hipaa/164_312/164_312_b.sp
- hipaa/164_312/164_312_e_2_ii.sp
- hipaa/docs/hipaa_overview.md
- hipaa/hipaa.sp
- policy_bundle/bigquery.sp
- policy_bundle/compute.sp
- policy_bundle/dataproc.sp
- policy_bundle/iam.sp
- policy_bundle/kms.sp
- policy_bundle/logging.sp
- policy_bundle/project.sp
- policy_bundle/resourcemanager.sp
- policy_bundle/sql.sp
- policy_bundle/storage.sp
> Add HIPAA benchmark

- policy_bundle/kms.sp
> Fixed the query 'kms_key_users_limited_to_3' fails due to hardcoded connection `gcp_parker` Closes  #169

- CHANGELOG.md
> Add CHANGELOG for v0.32

- CHANGELOG.md
> Add CHANGELOG for v0.33

- all_controls/alloydb.sp
- all_controls/project.sp
- policy_bundle/alloydb.sp
- policy_bundle/bigquery.sp
- policy_bundle/compute.sp
- policy_bundle/dataproc.sp
- policy_bundle/dns.sp
- policy_bundle/iam.sp
- policy_bundle/kms.sp
- policy_bundle/organization.sp
- policy_bundle/project.sp
- policy_bundle/resourcemanager.sp
- policy_bundle/sql.sp
- policy_bundle/storage.sp
- soc_2_2017/cc_2.sp
- soc_2_2017/cc_3.sp
- soc_2_2017/cc_4.sp
- soc_2_2017/cc_5.sp
- soc_2_2017/cc_6.sp
- soc_2_2017/cc_7.sp
- soc_2_2017/cc_8.sp
- soc_2_2017/docs/soc_2_2017_overview.md
- soc_2_2017/soc_2_2017.sp
> SOC 2 Compliance Feature for GCP closes #180

- cis_v120/section_6.pp
- cis_v130/section_6.pp
- cis_v200/section_6.pp
- policy_bundle/iam.pp
> Add GCP/SQL service tag to relevant controls and update IAM policy tags

- policy_bundle/compute.pp
> Patch title from 0.0.00/0 to 0.0.0.0/0

- policy_bundle/logging.pp
> fix: missing semicolon in logging.pp file

- nist_csf_v2/docs/nist_csf_v2_overview.md
- nist_csf_v2/nist_csf_v2.pp
- nist_csf_v2/nist_csf_v2_de.pp
- nist_csf_v2/nist_csf_v2_gv.pp
- nist_csf_v2/nist_csf_v2_id.pp
- nist_csf_v2/nist_csf_v2_pr.pp
- nist_csf_v2/nist_csf_v2_rc.pp
- nist_csf_v2/nist_csf_v2_rs.pp
- policy_bundle/bigquery.pp
- policy_bundle/cloudfunction.pp
- policy_bundle/compute.pp
- policy_bundle/dataproc.pp
- policy_bundle/iam.pp
- policy_bundle/kms.pp
- policy_bundle/kubernetes.pp
- policy_bundle/logging.pp
- policy_bundle/organization.pp
- policy_bundle/project.pp
- policy_bundle/resourcemanager.pp
- policy_bundle/sql.pp
- policy_bundle/storage.pp
> Add NIST CSF v2.0 Benchmark

- policy_bundle/sql.pp
```
select
self_link resource,
case
when ip_configuration ->> 'sslMode' = 'ENCRYPTED_ONLY' then 'ok'
else 'alarm'
end as status,
case
when ip_configuration ->> 'sslMode' = 'ENCRYPTED_ONLY'
then title || ' enforces SSL connections.'
else title || ' does not enforce SSL connections.'
end as reason
from
gcp_sql_database_instance;
+---------------------------------------------------------------------------------------+--------+-----------------------------------------------+
| resource                                                                              | status | reason                                        |
+---------------------------------------------------------------------------------------+--------+-----------------------------------------------+
| …
```
> Update query for control require_ssl_sql
